server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]': # Configuração de CORS global para todas as rotas
            allowedOrigins:
              - "http://localhost:4200" # Permite acesso a partir do frontend em localhost:4200
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders:
              - "Authorization"
              - "Content-Type"
              - "ngrok-skip-browser-warning" # to allow request from ngrok
            allowCredentials: true # Permite envio de cookies e credenciais
      routes:
        - id: receipt-scan
          uri: http://localhost:8082
          predicates:
            - Path=/receipt-scan/**
          filters:
            - StripPrefix=1
        - id: catalog
          uri: http://localhost:8083
          predicates:
            - Path=/catalog/**
          filters:
            - StripPrefix=1
        - id: register
          uri: http://localhost:8084
          predicates:
            - Path=/register/**
          filters:
            - StripPrefix=1
        - id: social
          uri: http://localhost:8085
          predicates:
            - Path=/social/**
          filters:
            - StripPrefix=1
        - id: auth
          uri: http://localhost:8086
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
