server:
  port: 8000

spring:
  application:
    name: gateway
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: receipt-bff
            client-secret: Jt0JvmekKSwfVuj2vqd0LoETyLnYxEd1
            scope: openid, email, profile
            redirect-uri: http://localhost:3000/callback
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/master
  cloud:
    gateway:
      routes:
        - id: resource
          uri: http://localhost:8082
          predicates:
            - Path=/resource
          filters:
            - TokenRelay=
        - id: receipt-scan
          uri: http://localhost:8082
          predicates:
            - Path=/receipt-scan/**
          filters:
            - StripPrefix=1
            - TokenRelay=
        - id: catalog
          uri: http://localhost:8083
          predicates:
            - Path=/catalog/**
          filters:
            - StripPrefix=1
            - TokenRelay=
        - id: user
          uri: http://localhost:8084
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
            - TokenRelay=
        - id: social
          uri: http://localhost:8085
          predicates:
            - Path=/social/**
          filters:
            - StripPrefix=1
            - TokenRelay=
